- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/continuous-integration-workflow.yml
- .gitignore
- Pipfile
- Pipfile.lock
- setup.py
- src/document_creator.py
- testdoc.py
This Pr introduces the first _minimal_ working state of the library. There will (probably) some Prs which changes the Project structure in the future.
> 🎉 Add Initial Function

- src/gdrive_tools.py
- testdoc.py
**Changes:**
1. Lets the user pass the path as a string in the following format: `path/to/the/new/file`. 
PR: #4
> ✨ Let the User Pass the Path as a String

- README.md
**Changes:**
1. Adds a Readme file which documents the purpose and basic usage of this module.
PR: #8
> 📝 Add a Readme

- src/gdrive_tools.py
- testdoc.py
**Changes:**
1. Adds a method which lets the user move a document from one directory to another. 
PR: #9
> ✨ Add a Method to Move a Document

- example.py
- requirements.txt
**Changes:**
1. Adds a Simple Example Script. 
PR: #11
> 📝 Add a Simple Example Script

- README.md
- example.py
- src/google_auth.py
**Changes:**
1. Adds a class which wraps the creation of the credentials.
PR: #13
> ✨ Create a Wrapper Class for the Google Authentication

- README.md
**Changes:**
1. Adds the `SCOPES` list, which defines the scopes
PR: #16
> Add the SCOPES for using the GDrive-API

- README.md
- example.py
**Changes:**
1. Updates the imports inside the readme and the example script.
PR: #?
> 📝 Update the Imports on the Readme and the Example Script

- gdrive_tools/gdrive_tools.py
**Changes:**
1. The `createDocument()` Method now returns the id of the created document.
PR: #18
> ✨Return the Id of a Created Document

- setup.py
**Changes:**
1. Fixes a bug where the needed google dependencies where not automatically installed, when installing this package from a wheel. 
PR: #19
> 🐛 Fix not Installed Subdependencies

- Jenkinsfile
- LICENSE
- example.py
**Changes:**
1. Adds a Jenkinsfile to let our Jenkins build and publish the gdrive tools package to PyPy.
2. Adds a LICENSE file.
PR: #?
> 👷‍♂️ Add Jenkinsfile

- setup.py
**Changes:**
1. Adds the `README.md` file to the `long_description` of the project.
2. Adds the `url` property, which points to the Repository of this project.
3. Adds the `license` property.
PR: #20
> 📝 Add Additional Package Information

- README.md
**Changes:**
1. Adds a more explicit documentation about the path syntax, used in the `createDocument()` and `movedDocument()` method. 
**Issues:**
References #21 
PR: #?
> 📝 Enhance the Documentation for the Path Syntax

- .pylintrc
- Pipfile
- Pipfile.lock
- gdrive_tools/gdrive_tools.py
**Changes:**
1. Adds a `pylintrc` file which sets up the basic pylint rules
2. Overhaul the complete code of the DriveTools module.
PR: #23
> 🎨 Enhance Code Style

- README.md
- example.py
- gdrive_tools/gdrive_tools.py
**Changes:**
1. Adds a `copyDocument(source, destination)` method which lets the user copy a document to a given location.
PR: #24
> ✨ Add a Method to Copy a Document

- README.md
- gdrive_tools/gdrive_tools.py
**Changes:**
1. Adds the `fillSheet()` method which lets the user fill a sheet with a provided Id.
PR: #25
> Add a Method to Fill a Sheet with Data

- README.md
- gdrive_tools/gdrive_tools.py
- gdrive_tools/google_accesslevel.py
- gdrive_tools/google_grant_type.py
**Changes:**
1. Adds the `grandApproval()` method which allows the user to share a document with a given id.
PR: #27
> Add a Method to Share a Document

- README.md
- gdrive_tools/gdrive_tools.py
**Changes:**
1. Adds an optional Keyword Argument which can be used to specify the name of the first sheet when creating a new sheet.
PR: #31
> Add a Parameter to Specify the Sheet Name when Creating a New Sheet

- README.md
- gdrive_tools/gdrive_tools.py
**Changes:**
1. Adds the ability to move and/or copy documents between different drives.
PR: #29
> ✨ Move and Copy Documents Between Different Drives

- README.md
- examples/README.md
- examples/copy_document.py
- examples/copy_document_between_shared_drives.py
- examples/copy_document_shared_drive.py
- examples/create_document.py
- examples/create_document_shared_drive.py
- examples/fill_and_read_a_sheet.py
- examples/grant_permissions.py
- examples/move_document.py
- examples/move_document_between_shared_drives.py
- examples/move_document_shared_drive.py
**Changes:**
1. Revises the Readme.
2. Adds some more examples.
PR: #30
> 📝 Revise the Readme and Examples

- README.md
- examples/read_directory.py
- gdrive_tools/gdrive_tools.py
**Changes:**
1. Adds the `readDirectory()` method which allows the user to read the content of a given directory.
PR: #34
> Add a Method to Read the Content of a Directory

- README.md
- examples/get_document_id.py
- examples/read_directory.py
- gdrive_tools/gdrive_tools.py
**Changes:**
1. Adds the `getDocumentId()` method, which returns the Id of a document, stored at a given path.
2. Refactors the `readDirectory()` method.
PR: #36
> Add a Method to Obtain the Id of a Document from a Path
